## Fundamentos de numpy

In [1]:
# Creación desde array
import numpy as np

# Desde una lista
lista = [1, 2, 3, 4]
array_1d = np.array(lista)
print("Array 1D:", array_1d)  # Salida: [1 2 3 4]

# Array 2D (matriz)
matriz = [[1, 2], [3, 4], [5, 6]]
array_2d = np.array(matriz)
print("Array 2D:\n", array_2d)
# Salida:
# [[1 2]
#  [3 4]
#  [5 6]]

# Arrays predefinidos
zeros = np.zeros((2, 3))  # Matriz 2x3 de ceros
print("Zeros:\n", zeros)
# Salida:
# [[0. 0. 0.]
#  [0. 0. 0.]]

ones = np.ones((2, 3))  # Matriz 2x3 de unos
print("Ones:\n", ones)
# Salida:
# [[1. 1. 1.]
#  [1. 1. 1.]]

# Secuencia con arange (similar a range de Python)
secuencia = np.arange(0, 10, 2)  # De 0 a 10 (excl.), paso de 2
print("Secuencia:", secuencia)  # Salida: [0 2 4 6 8]

# Array aleatorio
aleatorio = np.random.rand(2, 2)  # Matriz 2x2 con valores entre 0 y 1
print("Aleatorio:\n", aleatorio)
# Salida (varía): 
# [[0.123... 0.456...]
#  [0.789... 0.234...]]

Array 1D: [1 2 3 4]
Array 2D:
 [[1 2]
 [3 4]
 [5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Secuencia: [0 2 4 6 8]
Aleatorio:
 [[0.36010104 0.50604518]
 [0.1904997  0.13808236]]


In [2]:
# Inspección de los Arrays
print("Forma:", array_2d.shape)  # Salida: (3, 2)
print("Dimensiones:", array_2d.ndim)  # Salida: 2
print("Tipo de datos:", array_2d.dtype)  # Salida: int64 (o similar)

Forma: (3, 2)
Dimensiones: 2
Tipo de datos: int64


In [ ]:
# Operaciones Vectorizadas**

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Suma
print("Suma:", a + b)  # Salida: [5 7 9]

# Multiplicación elemento por elemento
print("Multiplicación:", a * b)  # Salida: [4 10 18]

# Operaciones con escalares
print("Escalar:", a * 2)  # Salida: [2 4 6]

In [ ]:
# Broadcasting

matriz = np.array([[1, 2, 3], [4, 5, 6]])
escalar = 10
print("Matriz + escalar:\n", matriz + escalar)
# Salida:
# [[11 12 13]
#  [14 15 16]]

vector = np.array([1, 0, -1])
print("Matriz + vector:\n", matriz + vector)
# Salida:
# [[1+1 2+0 3-1]
#  [4+1 5+0 6-1]] = [[2 2 2]
#                      [5 5 5]]

In [ ]:
# Slicing Básico**

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matriz original:\n", matriz)
# Salida:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

# Primera fila
print("Primera fila:", matriz[0])  # Salida: [1 2 3]

# Primera columna
print("Primera columna:", matriz[:, 0])  # Salida: [1 4 7]

# Submatriz 2x2 (esquina inferior derecha)
print("Submatriz:\n", matriz[1:, 1:])
# Salida:
# [[5 6]
#  [8 9]]

In [ ]:
# Slicing con Condiciones (Indexación Booleana)**


# Seleccionar valores mayores a 5
mask = matriz > 5
print("Valores > 5:", matriz[mask])  # Salida: [6 7 8 9]

# Reemplazar valores menores a 4 por 0
matriz[matriz < 4] = 0
print("Matriz modificada:\n", matriz)
# Salida:
# [[0 0 0]
#  [4 5 6]
#  [7 8 9]]

In [ ]:
# Funciones Estadísticas

datos = np.array([10, 20, 30, 40, 50])

print("Suma:", np.sum(datos))  # Salida: 150
print("Promedio:", np.mean(datos))  # Salida: 30.0
print("Desviación estándar:", np.std(datos))  # Salida: 14.142...
print("Máximo:", np.max(datos))  # Salida: 50
print("Mínimo:", np.min(datos))  # Salida: 10

In [ ]:
# Funciones Matemáticas

angulos = np.array([0, np.pi/2, np.pi])
print("Seno:", np.sin(angulos))  # Salida: [0. 1. 0.]
print("Raíz cuadrada:", np.sqrt(datos))  # Salida: [3.162... 4.472... 5.477... 6.324... 7.071...]

In [3]:
# Ejemplo final

import numpy as np

# Ejemplo 1: Creación de Arrays
lista = [1, 2, 3, 4]
array_1d = np.array(lista)
print("Array 1D:", array_1d)

matriz = [[1, 2], [3, 4], [5, 6]]
array_2d = np.array(matriz)
print("Array 2D:\n", array_2d)

zeros = np.zeros((2, 3))
print("Zeros:\n", zeros)

ones = np.ones((2, 3))
print("Ones:\n", ones)

secuencia = np.arange(0, 10, 2)
print("Secuencia:", secuencia)

aleatorio = np.random.rand(2, 2)
print("Aleatorio:\n", aleatorio)

# Ejemplo 2: Inspección de Arrays
print("Forma:", array_2d.shape)
print("Dimensiones:", array_2d.ndim)
print("Tipo de datos:", array_2d.dtype)

# Ejemplo 3: Operaciones Vectorizadas
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Suma:", a + b)
print("Multiplicación:", a * b)
print("Escalar:", a * 2)

# Ejemplo 4: Broadcasting
matriz = np.array([[1, 2, 3], [4, 5, 6]])
escalar = 10
print("Matriz + escalar:\n", matriz + escalar)
vector = np.array([1, 0, -1])
print("Matriz + vector:\n", matriz + vector)

# Ejemplo 5: Slicing Básico
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matriz original:\n", matriz)
print("Primera fila:", matriz[0])
print("Primera columna:", matriz[:, 0])
print("Submatriz:\n", matriz[1:, 1:])

# Ejemplo 6: Indexación Booleana
mask = matriz > 5
print("Valores > 5:", matriz[mask])
matriz[matriz < 4] = 0
print("Matriz modificada:\n", matriz)

# Ejemplo 7: Funciones Estadísticas
datos = np.array([10, 20, 30, 40, 50])
print("Suma:", np.sum(datos))
print("Promedio:", np.mean(datos))
print("Desviación estándar:", np.std(datos))
print("Máximo:", np.max(datos))
print("Mínimo:", np.min(datos))

# Ejemplo 8: Funciones Matemáticas
angulos = np.array([0, np.pi/2, np.pi])
print("Seno:", np.sin(angulos))
print("Raíz cuadrada:", np.sqrt(datos))

# Ejercicio Práctico
temperaturas = np.array([
    [15, 18, 20],
    [22, 21, 19],
    [10, 12, 15]
])
promedios = np.mean(temperaturas, axis=1)
print("Promedios por ciudad:", promedios)
max_temp = np.max(temperaturas)
ciudad_max = np.argmax(np.max(temperaturas, axis=1))
print(f"Temperatura máxima: {max_temp} en Ciudad {chr(65 + ciudad_max)}")
segundo_dia = temperaturas[:, 1]
print("Segundo día:", segundo_dia)
temperaturas[temperaturas < 15] = 15
print("Temperaturas ajustadas:\n", temperaturas)

Array 1D: [1 2 3 4]
Array 2D:
 [[1 2]
 [3 4]
 [5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Secuencia: [0 2 4 6 8]
Aleatorio:
 [[0.10482463 0.44229955]
 [0.1660367  0.19500229]]
Forma: (3, 2)
Dimensiones: 2
Tipo de datos: int64
Suma: [5 7 9]
Multiplicación: [ 4 10 18]
Escalar: [2 4 6]
Matriz + escalar:
 [[11 12 13]
 [14 15 16]]
Matriz + vector:
 [[2 2 2]
 [5 5 5]]
Matriz original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Primera fila: [1 2 3]
Primera columna: [1 4 7]
Submatriz:
 [[5 6]
 [8 9]]
Valores > 5: [6 7 8 9]
Matriz modificada:
 [[0 0 0]
 [4 5 6]
 [7 8 9]]
Suma: 150
Promedio: 30.0
Desviación estándar: 14.142135623730951
Máximo: 50
Mínimo: 10
Seno: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Raíz cuadrada: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Promedios por ciudad: [17.66666667 20.66666667 12.33333333]
Temperatura máxima: 22 en Ciudad B
Segundo día: [18 21 12]
Temperaturas ajustadas:
 [[15 18 20]
 [22 21 19]
 [15 15 15]]
