In [2]:
import numpy as np
notas_mates = np.random.randint(0,11, 10)
notas_fisica = np.random.randint(0, 11, 10)
alumnos = np.array(["Juan", "Pedro", "Antonio", "Maria", "Pablo", "Carlos", "Lucia",
"Marta", "Noelia", "Samuel"])
array_float = np.random.standard_normal(10)
print(notas_mates)
print(notas_fisica)

[5 0 6 5 0 1 9 9 8 1]
[9 6 3 6 9 2 4 2 6 3]


In [11]:
print(notas_mates[notas_mates < 5]+1)

print(np.where(notas_mates < 5, notas_mates+1, notas_mates))

[1 1 2 2]
[5 1 6 5 1 2 9 9 8 2]
