In [1]:
import numpy as np

# =====================================================================
# CARGA DEL ARCHIVO (PASO NECESARIO PARA TODAS LAS PREGUNTAS)
# =====================================================================

# Utilizamos np.genfromtxt() para cargar el archivo CSV.
# Se utiliza ',' como delimitador y se asume que los datos son homogéneos (mayormente numéricos),
# permitiendo que NumPy infiera el tipo de dato o use float por defecto [12, 13].

try:
    datos = np.genfromtxt("datos_estudiantes.csv", delimiter=',')
    print("--- Archivo cargado exitosamente ---")
except FileNotFoundError:
    print("Error: Asegúrate de que 'datos_estudiantes.csv' existe en el directorio.")
    # Si la carga falla, el script no puede continuar
    exit()

# Definición de las columnas para mayor claridad
ID = datos[:, 0]
NOTAS_MATES = datos[:, 1]
NOTAS_FISICA = datos[:, 2]
EDADES = datos[:, 3]

--- Archivo cargado exitosamente ---


In [2]:
print(NOTAS_MATES)
print(NOTAS_FISICA)
print(EDADES)

[1. 2. 0. ... 8. 3. 1.]
[2. 4. 0. ... 9. 1. 0.]
[24. 21. 20. ... 23. 24. 18.]


In [6]:
print("tamaño: ", datos.size)
print("dimensiones: ", datos.ndim)
print("forma: ", datos.shape)

tamaño:  40000
dimensiones:  2
forma:  (10000, 4)


In [8]:
nota_mates_m20 = NOTAS_MATES[EDADES <= 20]
print(nota_mates_m20)

[0. 3. 5. ... 5. 8. 1.]
